<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$this->view->info_usuario['nome']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<!-- Recuperando pelo as total_tweet definido na query do banco de dados -->
							<span class="perfilPainelItemValor"><?=$this->view->total_tweets['total_tweet']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->total_seguindo['total_seguindo']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->total_seguidores['total_seguidores']?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>
			<!-- A partir do foreach, estou listando o nome do usuário, o tweet e a data do usuário autenticado 
			e dos usuários seguidos por esse usuário autenticado (Confira em Tweet.php no método recuperarTweet()) -->
			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?> 
			<div class="row tweet">
				<div class="col">
					<p><strong><?=$tweet['nome']?></strong> <span class="text text-muted"><?=$tweet['data']?></span></p>
					<p><?=$tweet['tweet']?></p>

					<br />
					<!-- Como estamos exibindo tweets de usuários que estamos seguindo, não podemos 
					remover esses tweets porque não faz parte dos tweets do usuário autenticado e para
					isso precisamos remover o botão de remover dos tweets dos usuários que estamos seguindo.

					Como fazer isso?
					Bom, lembre-se que o objeto tweet possui o id_usuario, que é o id do usuário responsável
					pelo tweet, pois bem, e o usuário autenticado possui o id inserido na global $_SESSION,
					basta fazermos a seguinde comparação: Se o id contido na super global $_SESSION for
					igual ao id_usuario, iremos exibir o botão, pois significa que estamos logado no
					perfil do usuário autenticado, obviamente -->
					<?php if($tweet['id_usuario'] == $_SESSION['id']){ ?>
					<form method="get" action="/remover">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger" name="idTweet" value="<?=$tweet['id']?>"><small>Remover</small></button>
						</div>
					</form>
					<?php } ?>
				</div>
			</div>
		<?php } ?>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<!-- Irá para a rota quem_seguir, onde a action ocorre na AppController -->
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>